name: Release
on:
  push:
    branches: [ main, develop ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '23'
      - run: npm install
      - name: Reset CHANGELOG.md for main
        if: github.ref == 'refs/heads/main'
        run: echo "# New IDs Canoe Compensation Changelog" > CHANGELOG.md && git add CHANGELOG.md
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}