name: Release

on:
  push:
    branches: [ main ]

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - run: npm install
      - name: Run semantic-release
        id: semantic
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Debug release output
        run: |
          echo "Semantic-release exit code: ${{ steps.semantic.outcome }}"
          git tag -l
      - name: Set version
        id: set_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "Version set to: $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  package-and-upload:
    needs: release-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Create runtime artifact
        run: |
          mkdir -p release
          cp requirements.txt release/
          cp install.sh release/  # Copy from repo
          cp -r src release/
          cd release
          zip -r ../runtime-${{ needs.release-version.outputs.version }}.zip .
      - name: Debug outputs
        run: |
          echo "Version: ${{ needs.release-version.outputs.version }}"
      - name: Upload runtime artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-version.outputs.version }}
          files: ./runtime-${{ needs.release-version.outputs.version }}.zip
          name: runtime-${{ needs.release-version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}